### ISSUE TITLE
Kernel upgrade not possible in Fedora 38

### ISSUE THREAD

**Issue by OmegaRogue** [linux-surface/repo#12]
I was looking into why my system fails to upgrade to Fedora 39 or 40, and it seems that it fails to upgrade the kernel.
`sudo dnf --refresh upgrade` fails with the error
```
Error:
 Problem: The operation would result in removing the following protected packages: kernel-surface
```
using the options `--skip-broken` or `--nobest` also doesn't solve this.

**Comment by StollD** [comment]
https://github.com/linux-surface/linux-surface/issues/1159
