### ISSUE TITLE
Build kernel with f2fs module

### ISSUE THREAD

**Issue by Gobidev** [linux-surface/repo#8]
I have switched my filesystem over to f2fs, as it results in great performance on the EMMC storage of my Surface Go 1 4GB, but had to install a different kernel, as building linux-surface with the f2fs module would take very long on my Surface and I like to keep my kernel up-to-date. Therefore, it would be nice to have the f2fs module included in the linux-surface repository binaries (at least for the arch-repo). 

Edit: I hope this is the right place to post this.

**Comment by StollD** [comment]
Our builds use the same config as the respective upstream, we only add the surface specific options. So if arch has F2FS enabled (which is does: https://github.com/archlinux/svntogit-packages/blob/3b39577d2ed83108724c83c5e91dfced35e68459/trunk/config#L9546-L9559), it should work with our build too.

Did you test our builds? If yes, what was the error that you got? If not, please try that.

**Comment by qzed** [comment]
Closing as no reply. Should probably also be moved to https://github.com/linux-surface/linux-surface if it is still an issue.
