### ISSUE TITLE
Fedora 38 Packages

### ISSUE THREAD

**Issue by OmegaRogue** [linux-surface/repo#9]
I wanted to update to Fedora 38 today, but I got this message:
![image](https://user-images.githubusercontent.com/24958536/233045125-8afe31f0-699b-4e8d-9d76-6c5dbde5c0cf.png)
And it seems like there arent any packages for fedora 38 for surface linux stuff in the repo here yet, when are those going to be added?

**Comment by qzed** [comment]
Sorry, I somewhat forgot that the F38 release is today. I'll get on that right away.

**Comment by OmegaRogue** [comment]
Thanks, much appreciated!

**Comment by qzed** [comment]
Fedora 38 packages should now be available.
